### ISSUE TITLE
Assembly refactor and split

### ISSUE THREAD

**Issue by jviau** [microsoft/durabletask-dotnet#51]
As a first step towards enabling devs to author re-usable libraries for DurableTask .NET sdk, we will split the assemblies up. This will allow libraries to take in a minimal amount of dependencies. Each assembly will correspond to a NuGet package of the same name. The rough assembly layout will be:

| Name | Description |
| - | - |
| `Microsoft.DurableTask.Abstractions` | Contains base types for authoring and consuming orchestrations and activities |
| `Microsoft.DurableTask.Generators` | Contains the source generators. **note**: will be bundled into abstractions nuget package. |
| `Microsoft.DurableTask.Worker` | Contains the core framework for running a DTFx worker |
| `Microsoft.DurableTask.Worker.Grpc` | Contains the gRPC specific worker implementation |
| `Microsoft.DurableTask.Client` | Contains the durable task client and extensions. |
| `Microsoft.DurableTask.Client.Grpc` | Contains the gRPC client implementation for interacting with the DTFx backend |

## Tasks

- [x] Split assemblies
- [x] Public shim factory in worker package
- [x] Common durable task builder --> enable `services.AddDurableTask(b => b.UseGrpc());` secario
- [x] Allow for re-enterable builder --> enable multiple calls to `services.AddDurableTask(b => ..)`, all adding to the same builder.
- [ ] #73
- [x] Update code gen
- [x] Update samples.

**Comment by jviau** [comment]
> Microsoft.DurableTask.Generators

We can actually pack this analyzer up with `Microsoft.DurableTask.Abstractions` directly, so no need to reference them separately (will still be a separate csproj). @cgillum what do you think of that?

**Comment by cgillum** [comment]
@jviau I'm not sure if it's common practice to pack analyzers together with libraries. I feel like it could be problematic since the generator package contains a bunch of private assets, though I'll admit this is beyond my knowledge of how nuget packages work.

**Comment by jviau** [comment]
That is fair. I just noticed that `Microsoft.Extensons.Logging.Abstractions` packages its generator along with itself.

**Comment by cgillum** [comment]
Ah, then I guess there is precedent for this! I'm fine either way. If it's not too much work, it probably makes sense to keep these tightly bound to each other.

**Comment by jviau** [comment]
Okay, I will work on that then. Won't be part of the initial PR.

**Comment by jviau** [comment]
Mediator pattern is tracked in its own issue.
